version: '3.8'
services:
  hospital:
    image: revanth11/hospital-app
    container_name: hospital-app
    ports:
      - "8080:8081"
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge